update deploy-extension.yml file

diff --git a/.github/workflows/deploy-extension.yml b/.github/workflows/deploy-extension.yml
--- a/.github/workflows/deploy-extension.yml
+++ b/.github/workflows/deploy-extension.yml
@@ -12,20 +12,26 @@ jobs:
       - name: deploy-extension
         id: deploy-extension
         env:
-          ORG_NAME: ${{ secrets.ORG_NAME }}
-          USER_TOKEN: ${{ secrets.USER_TOKEN }}
+          PUBLISHER_NAME: ${{ secrets.PUBLISHER_NAME }}
+          ORGANIZATION_NAME: ${{ secrets.ORG_NAME }}
+          USER_TOKEN: ${{ secrets.USER_TOKEN }} #personal_access_token of azure devops account
         run: |
           vss_extension=$(cat vss-extension.json)
           extension_name=$(echo $vss_extension | jq -r '.name' )
-          extension_publisher=$(echo $vss_extension | jq -r '.publisher')  
+          echo "Extension Name:" $extension_name
           extension_version=$(echo $vss_extension | jq -r '.version')
-          echo "extension_name" $extension_name
-          echo "extension_publisher" $extension_publisher
-          echo "current version: " $extension_version
-          cat vss-extension.json
-          echo "Deploying $extension_name extension on $extension_publisher publisher  with latest-version: $extension_version"  
-          echo "Successful Deployed $extension_name extension on $extension_publisher publisher  with latest-version: $extension_version"  
-          echo "AZURE_EXTENSION_VERSION=$version"
+          echo "Extension Version:" $extension_version
+          echo "Installing tfx-cli..."
+          npm i -g tfx-cli
+          echo "Publishing extension $extension_name with version $extension_version"
+          tfx extension publish --publisher TestCIPub  --manifest-globs vss-extension.json  --token ${USER_TOKEN}  | tee tfx_output.log
+          publish_exit_code=${PIPESTATUS[0]}
+          if [ $publish_exit_code -eq 0 ]; then
+             echo "Extension $extension_name version $extension_version published successfully!"
+          else
+            echo "Failed to publish the extension $extension_name version $extension_version."
+            exit 1
+          fi
 
       - name: Upload Artifact
         uses: actions/upload-artifact@v4
