update publish-test.yml file

diff --git a/.github/workflows/publish-test.yml b/.github/workflows/publish-test.yml
--- a/.github/workflows/publish-test.yml
+++ b/.github/workflows/publish-test.yml
@@ -120,16 +120,16 @@ jobs:
           extension_version=$(echo $vss_extension_dev | jq -r '.version')
           echo "Extension Version:" $extension_version
           echo "Installing tfx-cli..."
-#          npm i -g tfx-cli
-#          echo "Publishing extension $extension_name with version $extension_version"
-#          tfx extension publish --publisher TestCIPub  --manifest-globs vss-extension-dev.json  --token ${USER_TOKEN} 2>&1 | tee tfx_output.log
-#          publish_exit_code=${PIPESTATUS[0]}
-#          if [ $publish_exit_code -eq 0 ]; then
-#             echo "Extension $extension_name version $extension_version published successfully!"
-#          else
-#            echo "Failed to publish the extension $extension_name version $extension_version."
-#            exit 1
-#          fi
+          npm i -g tfx-cli
+          echo "Publishing extension $extension_name with version $extension_version"
+          tfx extension publish --publisher TestCIPub  --manifest-globs vss-extension-dev.json  --token ${USER_TOKEN} 2>&1 | tee tfx_output.log
+          publish_exit_code=${PIPESTATUS[0]}
+          if [ $publish_exit_code -eq 0 ]; then
+             echo "Extension $extension_name version $extension_version published successfully!"
+          else
+            echo "Failed to publish the extension $extension_name version $extension_version."
+            exit 1
+          fi
 
 #  npm i -g tfx-cli
 #  tfx extension publish --publisher ${PUBLISHER_NAME}  --manifest-globs vss-extension-dev.json --share-with ${ORGANIZATION_NAME}  --token ${USER_TOKEN}
