update version

diff --git a/.github/workflows/publish-QAExtension.yml b/.github/workflows/publish-QAExtension.yml
--- a/.github/workflows/publish-QAExtension.yml
+++ b/.github/workflows/publish-QAExtension.yml
@@ -45,7 +45,8 @@ jobs:
           current_minor=$(echo $current_extension_version | awk -F. '{print $2}')
           current_patch=$(echo $current_extension_version | awk -F. '{print $3}')
           if [ "$previous_major" -eq "$current_major" ] && [ "$previous_minor" -eq "$current_minor" ]; then
-             new_version=$current_major.$current_minor.$((current_patch+1))
+             current_patch=$((current_patch+1))
+             new_version=$current_major.$current_minor.$current_patch
              echo "Updating extension version to: ${new_version}"
           
              echo "Updating vss-extension-dev.json with the new version: ${new_version}"
@@ -77,64 +78,68 @@ jobs:
              echo
           
              echo "Updating task.json with the new version: ${new_version}"
-             jq --argjson major_version $((current_major)) '.version.Major |= $major_version' && minor_version $((current_minor)) '.version.Minor |= $minor_version' && patch_version $((current_patch+1)) '.version.Patch |= $patch_version' task.json > task.json.tmp && mv task.json.tmp task.json
+             jq \
+             --arg major "$current_major" \
+             --arg minor "$current_minor" \
+             --arg patch "$current_patch" \
+             '.version.Major = ($major | tonumber) | .version.Minor = ($minor | tonumber ) .version.Patch = ($patch | tonumber) > task.json.tmp && mv task.json.tmp task.json
              echo "Updated task.json file"
              cat task.json
           echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
-
-      - name: publish-QAExtension
-        id: publish-qaextension
-        if: ${{  steps.version-update.conclusion == 'success'  }}
-        env:
-          PUBLISHER_NAME: ${{ secrets.PUBLISHER_NAME }}
-          ORGANIZATION_NAME: ${{ secrets.ORG_NAME }}
-          USER_TOKEN: ${{ secrets.USER_TOKEN }} #personal_access_token of azure devops account
-        run: |
-          vss_extension_dev=$(cat vss-extension-dev.json)
-          extension_name=$(echo $vss_extension_dev | jq -r '.name' )
-          echo "Extension Name:" $extension_name
-          extension_version=$(echo $vss_extension_dev | jq -r '.version')
-          echo "Extension Version:" $extension_version
-          echo "Install dependencies && Rebuild the dist/ directory"
-          cd synopsys-task && npm ci && npm run build && npm run package
-          cd ../
-          echo "Installing tfx-cli..."
-          npm i -g tfx-cli
-          echo "Creating extension $extension_name with version $extension_version"
-          npx tfx-cli extension create --manifest-globs vss-extension-dev.json
-          echo "Extension $extension_name created successfully!"
-          echo "Publishing extension $extension_name with version $extension_version"
-          publish_exit_code=${PIPESTATUS[0]}
-          if [ $publish_exit_code -eq 0 ]; then
-             echo "Extension $extension_name with version $extension_version published successfully!"
-          else
-            echo "Failed to publish the extension $extension_name with version $extension_version."
-            exit 1
-          fi
-
-#  npm i -g tfx-cli
-#  tfx extension publish --publisher ${PUBLISHER_NAME}  --manifest-globs vss-extension-dev.json --share-with ${ORGANIZATION_NAME}  --token ${USER_TOKEN} | tee tfx_output.log
-#  tfx extension publish --publisher TestCIPub  --manifest-globs vss-extension-dev.json  --token ${USER_TOKEN}  | tee tfx_output.log
-
-      - name: update extension version in file
-        id: update-extension-version
-        if: ${{  steps.publish-qaextension.conclusion == 'success' && env.NEW_VERSION != env.CURRENT_VERSION }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
-        run: |
-          echo "Updating extension version in vss-extension-dev.json, extension_version.txt, package.json, package-lock.json & task.json file"
-          git config --local user.name "$(git log -n 1 --pretty=format:%an)"
-          git config --local user.email "$(git log -n 1 --pretty=format:%ae)"
-          git add  vss-extension-dev.json extension_version.txt
-          cd synopsys-task
-          git add package.json package-lock.json task.json
-          git commit -m "update extension version [skip ci]"
-          git push origin main
-          echo "Successful updated extension version in vss-extension-dev.json, extension_version.txt, package.json, package-lock.json & task.json file..."
-#          git config --local user.name "github-actions[bot]"
-#          git config --local user.email "github-actions[bot]@users.noreply.github.com"
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ env.EXTENSION_NAME }}-${{ env.NEW_VERSION }}.vsix
-          path: "*.vsix"
+#  jq --argjson  patch_version  $((current_patch+1)) '.version.Patch |= $patch_version' task.json > task.json.tmp && mv task.json.tmp task.json
+#      - name: publish-QAExtension
+#        id: publish-qaextension
+#        if: ${{  steps.version-update.conclusion == 'success'  }}
+#        env:
+#          PUBLISHER_NAME: ${{ secrets.PUBLISHER_NAME }}
+#          ORGANIZATION_NAME: ${{ secrets.ORG_NAME }}
+#          USER_TOKEN: ${{ secrets.USER_TOKEN }} #personal_access_token of azure devops account
+#        run: |
+#          vss_extension_dev=$(cat vss-extension-dev.json)
+#          extension_name=$(echo $vss_extension_dev | jq -r '.name' )
+#          echo "Extension Name:" $extension_name
+#          extension_version=$(echo $vss_extension_dev | jq -r '.version')
+#          echo "Extension Version:" $extension_version
+#          echo "Install dependencies && Rebuild the dist/ directory"
+#          cd synopsys-task && npm ci && npm run build && npm run package
+#          cd ../
+#          echo "Installing tfx-cli..."
+#          npm i -g tfx-cli
+#          echo "Creating extension $extension_name with version $extension_version"
+#          npx tfx-cli extension create --manifest-globs vss-extension-dev.json
+#          echo "Extension $extension_name created successfully!"
+#          echo "Publishing extension $extension_name with version $extension_version"
+#          publish_exit_code=${PIPESTATUS[0]}
+#          if [ $publish_exit_code -eq 0 ]; then
+#             echo "Extension $extension_name with version $extension_version published successfully!"
+#          else
+#            echo "Failed to publish the extension $extension_name with version $extension_version."
+#            exit 1
+#          fi
+#
+##  npm i -g tfx-cli
+##  tfx extension publish --publisher ${PUBLISHER_NAME}  --manifest-globs vss-extension-dev.json --share-with ${ORGANIZATION_NAME}  --token ${USER_TOKEN} | tee tfx_output.log
+##  tfx extension publish --publisher TestCIPub  --manifest-globs vss-extension-dev.json  --token ${USER_TOKEN}  | tee tfx_output.log
+#
+#      - name: update extension version in file
+#        id: update-extension-version
+#        if: ${{  steps.publish-qaextension.conclusion == 'success' && env.NEW_VERSION != env.CURRENT_VERSION }}
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
+#        run: |
+#          echo "Updating extension version in vss-extension-dev.json, extension_version.txt, package.json, package-lock.json & task.json file"
+#          git config --local user.name "$(git log -n 1 --pretty=format:%an)"
+#          git config --local user.email "$(git log -n 1 --pretty=format:%ae)"
+#          git add  vss-extension-dev.json extension_version.txt
+#          cd synopsys-task
+#          git add package.json package-lock.json task.json
+#          git commit -m "update extension version [skip ci]"
+#          git push origin main
+#          echo "Successful updated extension version in vss-extension-dev.json, extension_version.txt, package.json, package-lock.json & task.json file..."
+##          git config --local user.name "github-actions[bot]"
+##          git config --local user.email "github-actions[bot]@users.noreply.github.com"
+#      - name: Upload Artifact
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: ${{ env.EXTENSION_NAME }}-${{ env.NEW_VERSION }}.vsix
+#          path: "*.vsix"
