update publish-test.yml file

diff --git a/.github/workflows/publish-test.yml b/.github/workflows/publish-test.yml
--- a/.github/workflows/publish-test.yml
+++ b/.github/workflows/publish-test.yml
@@ -43,21 +43,21 @@ jobs:
           current_major=$(echo $current_extension_version | awk -F. '{print $1}')
           current_minor=$(echo $current_extension_version | awk -F. '{print $2}')
           current_patch=$(echo $current_extension_version | awk -F. '{print $3}')
-          echo "previous:" $previous_major.$previous_minor
-          echo "current:" $current_major.$current_minor.$current_patch
           if [ "$previous_major" -eq "$current_major" ] && [ "$previous_minor" -eq "$current_minor" ]; then
              new_version=$current_major.$current_minor.$((current_patch+1)) 
-             echo "auto patch version updated to " $new_version
+             echo "Updating extension version to: ${new_version}"
              echo "NEW_VERSION=$version" >> $GITHUB_ENV    
+             echo "Updating vss-extension-dev.json with the new version: ${new_version}"
              jq --arg new_version "$new_version" '.version = $new_version' vss-extension-dev.json > vss-extension-dev.json.tmp && mv vss-extension-dev.json.tmp vss-extension-dev.json 
-             echo "vss-extension-dev.json file"
+             echo "Updated vss-extension-dev.json file"
              cat vss-extension-dev.json
+             echo "Updating extension_version.txt with the new version: ${new_version}"
              sed -i "s/extension_version=.*/extension_version=$new_version/" extension_version.txt
-             echo "extension_version.txt file"
+             echo "Updated extension_version.txt file"
              cat extension_version.txt
           else
-             echo "No auto version update"
              version=$current_extension_version
+             echo "Extension version will not be updated automatically. Current version: ${version}"
              echo "NEW_VERSION=$version" >> $GITHUB_ENV 
           fi  
 
@@ -70,11 +70,19 @@ jobs:
         run: |
            vss_extension_dev=$(cat vss-extension-dev.json)
            extension_name=$(echo $vss_extension_dev | jq -r '.name' )
-           echo "Extension-name: " $extension_name
+           echo "Extension Name: " $extension_name
            extension_version=$(echo $vss_extension_dev | jq -r '.version')
-           echo "Extension-version: " $extension_version
-           echo "Publishing extension with latest version: $extension_version"
-           echo "Successful published extension with latest version: $extension_version "
+           echo "Extension Version: " $extension_version
+           echo "Installing tfx-cli..."
+           npm i -g tfx-cli
+           echo "Publishing extension $extension_name with version $extension_version"
+           tfx extension publish --publisher  --manifest-globs vss-extension-dev.json 
+           if [ $? -eq 0 ]; then
+              echo "Extension $extension_name version $extension_version published successfully!"
+           else
+              echo "Failed to publish the extension. Please check the logs for more details."
+          exit 1
+          fi
 
 #  npm i -g tfx-cli
 #  tfx extension publish --publisher ${PUBLISHER_NAME}  --manifest-globs vss-extension-dev.json --share-with ${ORGANIZATION_NAME}  --token ${USER_TOKEN}
