update publish-test.yml file

diff --git a/.github/workflows/publish-test.yml b/.github/workflows/publish-test.yml
--- a/.github/workflows/publish-test.yml
+++ b/.github/workflows/publish-test.yml
@@ -66,6 +66,7 @@ jobs:
         env:
           PUBLISHER_NAME: ${{ secrets.PUBLISHER_NAME }}
           ORGANIZATION_NAME: ${{ secrets.ORG_NAME }}
+          USER_TOKEN: ${{ secrets.USER_TOKEN }} #personal_access_token of azure devops account
         run: |
           vss_extension_dev=$(cat vss-extension-dev.json)
           extension_name=$(echo $vss_extension_dev | jq -r '.name' )
@@ -75,15 +76,14 @@ jobs:
           echo "Installing tfx-cli..."
           npm i -g tfx-cli
           echo "Publishing extension $extension_name with version $extension_version"
-          exit 1
-#          tfx extension publish --publisher abcd  --manifest-globs vss-extension-dev.json --token aaa 2>&1 | tee tfx_output.log
-#          publish_exit_code=${PIPESTATUS[0]}
-#          if [ $publish_exit_code -eq 0 ]; then
-#             echo "Extension $extension_name version $extension_version published successfully!"
-#          else
-#            echo "Failed to publish the extension $extension_name version $extension_version."
-#            exit 1
-#          fi
+           tfx extension publish --publisher TestCIPub  --manifest-globs vss-extension-dev.json  --token ${USER_TOKEN} 2>&1 | tee tfx_output.log
+          publish_exit_code=${PIPESTATUS[0]}
+          if [ $publish_exit_code -eq 0 ]; then
+             echo "Extension $extension_name version $extension_version published successfully!"
+          else
+            echo "Failed to publish the extension $extension_name version $extension_version."
+            exit 1
+          fi
 
 #  npm i -g tfx-cli
 #  tfx extension publish --publisher ${PUBLISHER_NAME}  --manifest-globs vss-extension-dev.json --share-with ${ORGANIZATION_NAME}  --token ${USER_TOKEN}
@@ -138,20 +138,21 @@ jobs:
 ##          tfx extension publish --publisher TestCIPub  --manifest-globs vss-extension-dev.json --token ${USER_TOKEN}
 
 
-      - name: update extension version
-        id: update-extension-version
-        if: ${{  steps.publish-extension.conclusion == 'success' && env.NEW_VERSION != env.CURRENT_VERSION }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
-        run: |
-          echo "Updating version in vss-extension-dev.json..."
-          echo git config --local user.name "$(git log -n 1 --pretty=format:%an)"
-          echo git config --local user.email "$(git log -n 1 --pretty=format:%ae)"
-          git config --local user.name "github-actions[bot]"
-          git config --local user.email "github-actions[bot]@users.noreply.github.com"
-          git add vss-extension-dev.json extension_version.txt
-          git commit -m "update extension version [skip ci]"
-          echo "Successful updated version in vss-extension-dev.json..."
+#      - name: update extension version
+#        id: update-extension-version
+#        if: ${{  steps.publish-extension.conclusion == 'success' && env.NEW_VERSION != env.CURRENT_VERSION }}
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
+#        run: |
+#          echo "Updating version in vss-extension-dev.json..."
+#          echo git config --local user.name "$(git log -n 1 --pretty=format:%an)"
+#          echo git config --local user.email "$(git log -n 1 --pretty=format:%ae)"
+#          git config --local user.name "github-actions[bot]"
+#          git config --local user.email "github-actions[bot]@users.noreply.github.com"
+#          git add vss-extension-dev.json extension_version.txt
+#          git commit -m "update extension version [skip ci]"
+#          git push origin main
+#          echo "Successful updated version in vss-extension-dev.json..."
 
 #      - name: Upload Artifact
 #        uses: actions/upload-artifact@v4
