update publish-test.yml file

diff --git a/.github/workflows/publish-test.yml b/.github/workflows/publish-test.yml
--- a/.github/workflows/publish-test.yml
+++ b/.github/workflows/publish-test.yml
@@ -75,14 +75,15 @@ jobs:
           echo "Installing tfx-cli..."
           npm i -g tfx-cli
           echo "Publishing extension $extension_name with version $extension_version"
-          tfx_output=$(tfx extension publish --publisher abcd  --manifest-globs vss-extension-dev.json --token aaa 2>&1)
-          echo $tfx_output 
-          publish_exit_code=$?
+          tfx extension publish --publisher abcd  --manifest-globs vss-extension-dev.json --token aaa 2>&1 | tee tfx_output.log
+          publish_exit_code=${PIPESTATUS[0]}
           echo $publish_exit_code "code"
           if [ $publish_exit_code -eq 0 ]; then
              echo "Extension $extension_name version $extension_version published successfully!"
           else
             echo "Failed to publish the extension. Please check the logs for more details."
+            echo "Error details:"
+            cat tfx_output.log
             exit 1
           fi
 
