update publish-test.yml file

diff --git a/.github/workflows/publish-test.yml b/.github/workflows/publish-test.yml
--- a/.github/workflows/publish-test.yml
+++ b/.github/workflows/publish-test.yml
@@ -75,14 +75,14 @@ jobs:
           echo "Installing tfx-cli..."
           npm i -g tfx-cli
           echo "Publishing extension $extension_name with version $extension_version"
-          tfx extension publish --publisher abcd  --manifest-globs vss-extension-dev.json --token aaa 2>&1 | tee tfx_output.log
-          publish_exit_code=${PIPESTATUS[0]}
-          if [ $publish_exit_code -eq 0 ]; then
-             echo "Extension $extension_name version $extension_version published successfully!"
-          else
-            echo "Failed to publish the extension $extension_name version $extension_version."
-            exit 1
-          fi
+#          tfx extension publish --publisher abcd  --manifest-globs vss-extension-dev.json --token aaa 2>&1 | tee tfx_output.log
+#          publish_exit_code=${PIPESTATUS[0]}
+#          if [ $publish_exit_code -eq 0 ]; then
+#             echo "Extension $extension_name version $extension_version published successfully!"
+#          else
+#            echo "Failed to publish the extension $extension_name version $extension_version."
+#            exit 1
+#          fi
 
 #  npm i -g tfx-cli
 #  tfx extension publish --publisher ${PUBLISHER_NAME}  --manifest-globs vss-extension-dev.json --share-with ${ORGANIZATION_NAME}  --token ${USER_TOKEN}
@@ -139,7 +139,7 @@ jobs:
 
       - name: update extension version
         id: update-extension-version
-        if: ${{ env.NEW_VERSION != env.CURRENT_VERSION }}
+        if: ${{  steps.publish-extension.conclusion == 'success' && env.NEW_VERSION != env.CURRENT_VERSION }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
         run: |
