extension version-upgrade

diff --git a/.github/workflows/publish-synopsys-extension.yml b/.github/workflows/publish-synopsys-extension.yml
--- a/.github/workflows/publish-synopsys-extension.yml
+++ b/.github/workflows/publish-synopsys-extension.yml
@@ -8,12 +8,53 @@ jobs:
     if: "!contains(github.event.head_commit.message, '[skip ci]')"
     runs-on: ubuntu-latest
     steps:
-
+      - uses: actions/checkout@v4
 
       - name: Set Node.js 20.x
         uses: actions/setup-node@v4
         with:
           node-version: 20.x
 
-      - name: Rebuild the dist/ directory
-        uses: ./.github/workflows/check-dist.yml
+      - name: Compare the expected and actual dist/ directories
+        run: |
+          cd synopsys-task
+          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
+            echo "Detected uncommitted changes after build.  See status below:"
+            git diff
+            exit 1
+          fi
+        id: diff
+
+      - name: publish-Extension
+        id: publish-extension
+        env:
+          PROD_PUBLISHER_NAME: ${{ secrets.PROD_PUBLISHER_NAME }}
+          PROD_ORGANIZATION_NAME: ${{ secrets.PROD_ORG_NAME }}
+          PROD_USER_TOKEN: ${{ secrets.PROD_USER_TOKEN }} #personal_access_token of azure devops account
+        run: |
+          vss_extension_dev=$(cat vss-extension.json)
+          extension_name=$(echo $vss_extension | jq -r '.name' )
+          echo "Extension Name:" $extension_name
+          extension_version=$(echo $vss_extension | jq -r '.version')
+          echo "Extension Version:" $extension_version
+          echo "Installing tfx-cli..."
+          npm i -g tfx-cli
+          echo "Creating extension $extension_name with version $extension_version"
+          npx tfx-cli extension create --manifest-globs vss-extension.json
+          echo "Extension $extension_name created successfully!"
+          echo "Publishing extension $extension_name with version $extension_version"
+          publish_exit_code=${PIPESTATUS[0]}
+          if [ $publish_exit_code -eq 0 ]; then
+             echo "Extension $extension_name with version $extension_version published successfully!"
+          else
+            echo "Failed to publish the extension $extension_name with version $extension_version."
+            exit 1
+          fi
+          
+
+      - name: Upload Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ env.EXTENSION_NAME }}-${{ env.NEW_VERSION }}.vsix
+          path: "*.vsix"
+
